services:
  powkedex:
    container_name: powkedex
    # build a docker image from a context
    build: 
      context: ./app
      dockerfile: dev.Dockerfile
    # Set environment variables directly in the compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
       - ./app/src:/app/src
       - ./app/public:/app/public
    ports:
      - "3000:3000"
    restart: always
    networks:
      - nginxpm
      
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  nginxpm:
    external: true